### PR TITLE
Fix CPANTS Kwalitee issues

### PR DESCRIPTION
**Pull request by zakame**
This PR is a submission for my [CPAN Pull Request Challenge this month](http://cpan-prc.org/2018/january.html).

This implements fixes for extra [Kwalitee issues](https://cpants.cpanauthors.org/dist/Lingua-EN-Inflect-Phrase):

  - Declare minimum Perl version
  - Declare modules provided by this dist

### CODE REVIEW

**Comment by rkitover** [comment]
Oh oops I completely missed this one, I'll merge it now.

**Comment by rkitover** [comment]
Released 0.20 with your fixes, thank you!

**Comment by zakame** [comment]
Thanks! :tada:

**Comment by rkitover** [comment]
I'm going to try to update @AVAR with these two modules as well.

Sorry, didn't mean to ping you, I meant the dzil plugin 🤦‍♂️

**Comment by avar** [comment]
@rkitover A lot of people have tried and failed to update me with proper English pluralization rules, good luck.

:)

**Pull request merged**
